############################
## CHANGE THESE
############################

baseURL: 'https://badowhp.github.io'
title: 'DevOps Master Class'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


