############################
## German Navbar
############################

main:
- name: "Home"
  url: "/de/"
  weight: 10
- name: "Services"
  url: "/de/services/"
  weight: 20
- name: "Blog"
  url: "/de/blog/"
  weight: 30
- name: "About"
  url: "/de/about/"
  weight: 40